---
title: "Tropi Physical Monitoring - Analysis of Test Sensitivity"
author: "Dan Aurell"
date: "2025-02-24"
output: 
  html_document:
    keep_md: yes
---

# Setup
```{r}
library(tidyverse)
library(MASS)
library(lme4)
library(ggpubr)
library(broom)
library(gt)
library(multcomp)
library(emmeans)
library(DHARMa)
```



# Sensitivity - detection rate by sample method

## Make a sensitivity table - estimated detection rate by sample method
```{r}
table_percent_detection_core <- datum_long %>% 
  filter(core == 1) %>% 
  group_by(target, test) %>% 
  summarise(n = n(),
            nas = sum(is.na(detect01)),
            detect_n = sum(detect01, na.rm = TRUE),
            nondetect_n = n - nas - detect_n,
            denom = detect_n + nondetect_n,
            perc_detect = 100*detect_n/denom,
            ) %>% 
  arrange(target, desc(perc_detect))

write.csv(table_percent_detection_core, "./outputs/table_percent_detection_core.csv")
```

## Sensitivity - Analyze Tropilaelaps detection rate by sample method
```{r}
# [This first approach - which did not consider the clustering of observations 
# in colonies - has been superseded by the mixed modeling approach below]

# Using the datum_long data frame because I do want to make comparisons with also uncapping 
names(datum_long)
unique(datum_long$test)

# Only Tropi
sub_tropi_detect <- datum_long %>% 
  filter(core == 1,
         target == "tropi"
         )

# Fit null model and another with test type as a predictor
m.detect.0 <- glm(detect01 ~ 1, family = binomial, data = sub_tropi_detect)
m.detect.1 <- glm(detect01 ~ test, family = binomial, data = sub_tropi_detect)

anova(m.detect.0, m.detect.1, test = "Chisq")
# Results: Monitoring method had a significant impact on the probability of detecting Tropilaelaps mites from a colony (Chisq = 51.004, df = 4, P < 0.001)

TukeyHSD(aov(m.detect.1))
# Results: 
# (expressed in CLD)
# sticky ^ a
# infest100 ^ a
# bump ^ a
# powsug ^ b
# alc ^ b

paircomp_tropi <- tidy(TukeyHSD(aov(m.detect.1)))


# Same but in a mixed-effects framework
m.detect.mm.0 <- glmer(detect01 ~ 1 + (1|colony_id), family = binomial, data = sub_tropi_detect)
m.detect.mm.1 <- glmer(detect01 ~ test + (1|colony_id), family = binomial, data = sub_tropi_detect)

anova(m.detect.mm.0, m.detect.mm.1, test = "Chisq")
# Results: Monitoring method had a significant impact on the probability of detecting Tropilaelaps mites from a colony (Chisq = 73.849, df = 4, P < 0.001)

emmeans(m.detect.mm.1, pairwise ~ test, type = "response")$contrasts
emmeans(m.detect.mm.1, ~test, type = "response")

paircomp_tropi2 <- tidy(emmeans(m.detect.mm.1, pairwise ~ test, type = "response")$contrasts)

# Results: 
# (expressed in CLD)
# sticky ^ a
# infest100 ^ b
# bump ^ c
# powsug ^ d
# alc ^ d

simulateResiduals(m.detect.mm.1, plot = T) # OK
testDispersion(m.detect.mm.1) # OK
testZeroInflation(m.detect.mm.1) # OK


```


```{r}
# Nice Tropi pairwise comparisons table with gt

tbl.paircomp_tropi <- gt(paircomp_tropi2) %>% 
  fmt_number(
    columns = c("adj.p.value"),
    decimals = c(6))

tbl.paircomp_tropi <- tbl.paircomp_tropi %>%
  as_rtf()

my_conn <- file("./outputs/paircomp_tropi_2026-02-08.RTF", "w")
  writeLines(tbl.paircomp_tropi, my_conn)
close(my_conn)
```


## Sensitivity - Analyze Varroa detection rate by sample method
```{r}
# Using the datum_long data frame because I do want to make comparisons with also uncapping 

names(datum_long)
unique(datum_long$test)

# For Varroa, need to omit sticky board and bump since did not record Varroa on them
sub_varroa_detect <- datum_long %>% 
  filter(core == 1,
         target == "tropi",
         test %in% c("infest200", "powsug", "alc")
         )

# Mixed model framework

# Same but in a mixed-effects framework
m.detect.varroa.mm.0 <- glmer(detect01 ~ 1 + (1|colony_id), family = binomial, data = sub_varroa_detect)
m.detect.varroa.mm.1 <- glmer(detect01 ~ test + (1|colony_id), family = binomial, data = sub_varroa_detect)

anova(m.detect.varroa.mm.0, m.detect.varroa.mm.1, test = "Chisq")
# Results: Monitoring method had a significant impact on the probability of detecting Varroa mites from a colony (Chisq = 37.471, df = 2, P < 0.001)

emmeans(m.detect.varroa.mm.1, pairwise ~ test, type = "response")$contrasts
emmeans(m.detect.varroa.mm.1, ~test, type = "response")

paircomp_varroa2 <- tidy(emmeans(m.detect.varroa.mm.1, pairwise ~ test, type = "response")$contrasts)

# Results: 
# (expressed in CLD)
# powsug ^ a
# alc ^ a
# infest100 ^ b


simulateResiduals(m.detect.varroa.mm.1, plot = T) # OK
testDispersion(m.detect.varroa.mm.1) # OK
testZeroInflation(m.detect.varroa.mm.1) # OK
```


```{r}
# Nice Varroa pairwise comparisons table with gt

tbl.paircomp_varroa <- gt(paircomp_varroa2) %>% 
  fmt_number(
    columns = c("adj.p.value"),
    decimals = c(6))

tbl.paircomp_varroa <- tbl.paircomp_varroa %>%
  as_rtf()

my_conn <- file("./outputs/paircomp_varroa_2026-02-08.RTF", "w")
  writeLines(tbl.paircomp_varroa, my_conn)
close(my_conn)
```



# Explore the similarity between sugar shake and alcohol wash

## Calculate percent agreement
```{r}
datum_core <- datum %>% 
  filter(core == 1)

datum_core2 <- datum %>% 
  filter(core == 1,
         tropi_alc < 25)

datum_core <- datum_core %>% 
  mutate(powsug01 = if_else(tropi_powsug > 0, 1, 0),
         alc01 = if_else(tropi_alc > 0, 1, 0),
         agree = if_else(powsug01 + alc01 == 1, 0, 1)
         )

sum(datum_core$agree)
21/26 # = 81%


```





